# Generated by Django 3.2 on 2021-05-06 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_rename_websitecontent_webpagecontent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='webpagecontent',
            name='webpage',
        ),
    ]
