# Generated by Django 3.2 on 2021-05-06 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_remove_webpagecontent_webpage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webpagecontent',
            name='description',
            field=models.TextField(default='', max_length=5000),
        ),
        migrations.AlterField(
            model_name='webpagecontent',
            name='image',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='webpagecontent',
            name='subtitle',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='webpagecontent',
            name='title',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='webpagecontent',
            name='url',
            field=models.CharField(default='', max_length=150),
        ),
    ]
