# Generated by Django 3.2 on 2021-05-06 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_auto_20210505_2319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webpagecontent',
            name='description',
            field=models.TextField(blank=True, max_length=5000),
        ),
        migrations.AlterField(
            model_name='webpagecontent',
            name='image',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='webpagecontent',
            name='subtitle',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='webpagecontent',
            name='title',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='webpagecontent',
            name='url',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
