# Generated by Django 3.2 on 2021-05-06 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_auto_20210505_2323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webpagecontent',
            name='image',
            field=models.ImageField(default='default.png', upload_to='upload_images'),
        ),
    ]
