# Generated by Django 3.2 on 2021-05-07 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_webpagecontent_fontaweomeicons'),
    ]

    operations = [
        migrations.RenameField(
            model_name='webpagecontent',
            old_name='fontaweomeicons',
            new_name='fontaweomeicons_one',
        ),
        migrations.AddField(
            model_name='webpagecontent',
            name='fontaweomeicons_three',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='webpagecontent',
            name='fontaweomeicons_two',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
