# Generated by Django 3.2 on 2021-05-07 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_auto_20210507_0156'),
    ]

    operations = [
        migrations.AddField(
            model_name='webpage',
            name='fa_icon',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='webpage',
            name='url',
            field=models.CharField(default='', max_length=100),
        ),
    ]
